# Generated by Django 4.1.7 on 2023-03-03 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("importer", "0002_category_main_text_alter_blob_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="blob",
            name="priority",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
