# Generated by Django 4.1.7 on 2023-03-05 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("importer", "0003_blob_priority"),
    ]

    operations = [
        migrations.AddField(
            model_name="blob",
            name="neighborhoods",
            field=models.ManyToManyField(
                blank=True, related_name="blob_m2m", to="importer.neighborhood"
            ),
        ),
        migrations.AddField(
            model_name="blob",
            name="soft_delete",
            field=models.BooleanField(default=False),
        ),
    ]
