# Generated by Django 4.1.7 on 2023-03-05 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("importer", "0005_remove_blob_neighborhoods"),
    ]

    operations = [
        migrations.AddField(
            model_name="blob",
            name="categories",
            field=models.ManyToManyField(
                blank=True, related_name="blob_m2m", to="importer.category"
            ),
        ),
    ]
