# Generated by Django 4.1.7 on 2023-03-05 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("importer", "0007_remove_blob_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="blob",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="importer.category",
            ),
        ),
    ]
