# Generated by Django 4.1.7 on 2023-03-09 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("importer", "0009_remove_blob_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="section",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="importer.section",
            ),
        ),
    ]
