# Generated by Django 4.1.7 on 2023-03-10 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("importer", "0010_category_section"),
    ]

    operations = [
        migrations.AddField(
            model_name="blob",
            name="order",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
