# Generated by Django 4.1.7 on 2023-06-19 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("importer", "0012_category_order_neighborhood_order_section_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="blob",
            name="category_text",
            field=models.TextField(blank=True, null=True),
        ),
    ]
