# Generated by Django 4.1.7 on 2023-06-19 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("importer", "0013_blob_category_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blob",
            name="category_text",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
