# Generated by Django 4.1.7 on 2023-09-24 17:15

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lname", models.CharField(max_length=200)),
                ("fname", models.CharField(blank=True, max_length=200, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("order", models.IntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ["lname", "order"],},
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "book_type",
                    models.CharField(
                        choices=[("NF", "nonfiction"), ("TG", "travelguide")],
                        default="NF",
                        max_length=200,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "language",
                    models.CharField(
                        choices=[("EN", "English"), ("DE", "German")],
                        default="EN",
                        max_length=200,
                    ),
                ),
                (
                    "isbn",
                    models.CharField(
                        blank=True,
                        help_text="EX: isbn-000-0-000-00000-0",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        blank=True,
                        help_text="/ separated html. Example: 'COOKING / Courses &amp; Dishes / General'",
                        max_length=200,
                        null=True,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "author",
                    models.ManyToManyField(blank=True, to="ebook_exporter.author"),
                ),
            ],
            options={"ordering": ["title"],},
        ),
        migrations.CreateModel(
            name="StaticFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("fonts", "fonts"),
                            ("images", "images"),
                            ("css", "css"),
                        ],
                        default="css",
                        max_length=200,
                    ),
                ),
                ("upload", models.FileField(upload_to="exporter/static/")),
            ],
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("caption", models.CharField(blank=True, max_length=200, null=True)),
                ("img", models.ImageField(upload_to="img")),
                ("needsCitation", models.BooleanField(default=False)),
                (
                    "book",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ebook_exporter.book",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="book",
            name="cover",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bookcover",
                to="ebook_exporter.image",
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="files",
            field=models.ManyToManyField(blank=True, to="ebook_exporter.staticfile"),
        ),
        migrations.CreateModel(
            name="Chapter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("display_title", models.BooleanField(default=True)),
                (
                    "playOrder",
                    models.IntegerField(
                        default=2,
                        validators=[django.core.validators.MinValueValidator(2)],
                    ),
                ),
                ("publish", models.BooleanField(default=True)),
                ("src", models.CharField(blank=True, max_length=200)),
                (
                    "media_type",
                    models.CharField(
                        choices=[
                            ("jpg", "image/jpeg"),
                            ("html", "application/xhtml+xml"),
                            ("dtbncx", "application/x-dtbncx+xml"),
                            ("css", "text/css"),
                            ("vnd", "application/vnd.ms-opentype"),
                        ],
                        default="html",
                        max_length=200,
                    ),
                ),
                ("bodyText", models.TextField(blank=True, null=True)),
                (
                    "book",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="ebook_exporter.book",
                    ),
                ),
            ],
            options={
                "ordering": ["playOrder"],
                "unique_together": {("title", "book"), ("book", "src")},
            },
        ),
    ]
