# Generated by Django 4.1.7 on 2023-10-08 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ebook_exporter", "0003_auto_20231008_1401"),
    ]

    operations = [
        migrations.AddField(
            model_name="chapter",
            name="chapter_type",
            field=models.CharField(
                choices=[
                    ("TP", "Title Page"),
                    ("CR", "Copyright"),
                    ("C", "Contents"),
                    ("CH", "Chapter"),
                ],
                default="CH",
                max_length=200,
            ),
        ),
    ]
