# Generated by Django 4.1.7 on 2025-02-01 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ebook_exporter", "0005_footertransport"),
    ]

    operations = [
        migrations.CreateModel(
            name="FooterDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("BTS", "BTS"),
                            ("MRT", "MRT"),
                            ("K", "Kanalboot"),
                            ("F", "Flussboot"),
                            ("A", "Address"),
                            ("GM", "Google Maps"),
                        ],
                        default="BTS",
                        max_length=5,
                    ),
                ),
                ("text", models.CharField(max_length=200)),
                ("mins", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("url", models.URLField(blank=True, null=True)),
                (
                    "subsection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ebook_exporter.subsection",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(name="FooterTransport",),
    ]
