# Generated by Django 4.1.7 on 2025-02-03 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ebook_exporter", "0006_footerdetail_delete_footertransport"),
    ]

    operations = [
        migrations.AlterField(
            model_name="footerdetail",
            name="type",
            field=models.CharField(
                choices=[
                    ("BTS", "BTS"),
                    ("BTSG", "BTS Gold"),
                    ("ARL", "ARL"),
                    ("BRT", "BRT"),
                    ("MRT", "MRT"),
                    ("MRTPK", "MRT Pink"),
                    ("MRTPPL", "MRT Purple"),
                    ("MRTYLW", "MRT Yellow"),
                    ("SRT", "SRT"),
                    ("SRTLR", "SRT Light Red"),
                    ("SRTDR", "SRT Dark Red"),
                    ("K", "Kanalboot"),
                    ("F", "Flussboot"),
                    ("W", "Website"),
                    ("GM", "Google Maps"),
                ],
                default="BTS",
                max_length=7,
            ),
        ),
    ]
