# Generated by Django 4.1.7 on 2025-02-15 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ebook_exporter", "0007_alter_footerdetail_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="footerdetail",
            name="subsection",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="footer_details",
                to="ebook_exporter.subsection",
            ),
        ),
    ]
