# Generated by Django 4.1.7 on 2025-12-21 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebook_exporter', '0008_alter_footerdetail_subsection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footerdetail',
            name='type',
            field=models.CharField(choices=[('BTS', 'BTS'), ('BTSG', 'BTS Gold'), ('BTSLG', 'BTS Light Green'), ('BTSDG', 'BTS Dark Green'), ('ARL', 'ARL'), ('BRT', 'BRT'), ('MRT', 'MRT'), ('MRTPK', 'MRT Pink'), ('MRTPPL', 'MRT Purple'), ('MRTYLW', 'MRT Yellow'), ('SRT', 'SRT'), ('SRTLR', 'SRT Light Red'), ('SRTDR', 'SRT Dark Red'), ('K', 'Kanalboot'), ('F', 'Flussboot'), ('W', 'Website'), ('GM', 'Google Maps')], default='BTS', max_length=7),
        ),
    ]
